#include "phylter2/distatis.hpp"
#include "phylter2/newick.hpp"
#include "phylter2/preparation.hpp"
#include "phylter2/statistics.hpp"

#include <cmath>
#include <cstdlib>
#include <iostream>
#include <limits>
#include <stdexcept>
#include <vector>

namespace {

void require(const bool condition, const char* message) {
  if (!condition) throw std::runtime_error(message);
}
template<class Function> void rejects(Function function, const char* message) {
  try { function(); } catch (const std::exception&) { return; }
  throw std::runtime_error(message);
}

void require_near(const double actual, const double expected, const double tolerance,
                  const char* message) {
  if (!std::isfinite(actual) || !std::isfinite(expected) ||
      std::abs(actual - expected) > tolerance) throw std::runtime_error(message);
}

phylter2::Matrix distances(const std::initializer_list<double> values) {
  phylter2::Matrix result(4, 4);
  auto source = values.begin();
  for (std::size_t row = 0; row < 4; ++row) {
    for (std::size_t col = 0; col < 4; ++col) result(row, col) = *source++;
  }
  return result;
}

phylter2::GeneMatrix gene(std::string id, std::vector<std::string> taxa,
                          const std::initializer_list<double> values) {
  const std::size_t size = taxa.size();
  phylter2::Matrix matrix(size, size);
  auto source = values.begin();
  for (std::size_t row = 0; row < size; ++row) {
    for (std::size_t col = 0; col < size; ++col) matrix(row, col) = *source++;
  }
  return {.gene = std::move(id), .distances = {.values = std::move(matrix), .taxa = std::move(taxa)}};
}

}  // namespace

int main() {
  try {
    rejects([] { (void)phylter2::parse_newick("(A:1,B:2,C:3)"); }, "unterminated tree accepted");
    rejects([] { (void)phylter2::parse_newick("(A:nan,B:2,C:3);"); }, "NaN branch accepted");
    rejects([] { (void)phylter2::patristic_distances(phylter2::parse_newick("(A:1,A:2,C:3);")); },
            "duplicate taxa accepted");
    rejects([] { (void)phylter2::Matrix(std::numeric_limits<std::size_t>::max(),2); },
            "matrix overflow accepted");
    rejects([] { (void)phylter2::medcouple({0,std::numeric_limits<double>::infinity()}); },
            "infinite medcouple input accepted");
    const std::string bounded = "(A:1,B:2,C:3);trailing";
    require(phylter2::parse_newick(std::string_view(bounded.data(),bounded.find(';')+1)).nodes.size()==4,
            "non-terminated Newick view mishandled");
    require(phylter2::parse_newick_set("[comment] (A:1,B:2,C:3); ('semi;colon':2,B:3,C:4);").size()==2,
            "multi-tree parsing failed");
    const auto nodal = phylter2::patristic_distances(phylter2::parse_newick("((A,B),C,D);"),true);
    require_near(nodal.values(0,1),1,0,"nodal sibling distance mismatch");
    require_near(nodal.values(0,2),2,0,"nodal distance mismatch");
    const std::vector<phylter2::Matrix> matrices{
      distances({0, 2, 4, 5, 2, 0, 3, 4, 4, 3, 0, 2, 5, 4, 2, 0}),
      distances({0, 2, 5, 5, 2, 0, 4, 3, 5, 4, 0, 2, 5, 3, 2, 0}),
      distances({0, 3, 4, 6, 3, 0, 3, 5, 4, 3, 0, 2, 6, 5, 2, 0})};
    const phylter2::DistatisResult result = phylter2::distatis(matrices, 2);
    require(result.rv.rows() == 3 && result.rv.cols() == 3, "wrong RV dimensions");
    require(result.coordinates.rows() == 4 && result.coordinates.cols() == 2,
            "wrong coordinate dimensions");
    require(result.partial_coordinates.size() == 3, "wrong number of partial coordinates");
    require(std::abs(result.alpha[0] + result.alpha[1] + result.alpha[2] - 1.0) < 1e-12,
            "weights do not sum to one");
    // These values were generated by the unchanged R 0.9.12 implementation
    // with DistatisFast(..., factorskept = 2, parallel = FALSE). Eigenvector
    // signs are arbitrary, so coordinates are compared through their Gram matrix.
    const std::vector<double> expected_alpha{0.336952261538517, 0.330468343019654,
                                             0.332579395441830};
    for (std::size_t i = 0; i < expected_alpha.size(); ++i) {
      require_near(result.alpha[i], expected_alpha[i], 1e-12, "R/C++ alpha mismatch");
    }
    require_near(result.quality, 0.975370518494933, 1e-12, "R/C++ quality mismatch");
    for (std::size_t row = 0; row < result.rv.rows(); ++row) {
      require(std::abs(result.rv(row, row) - 1.0) < 1e-12, "RV diagonal is not one");
      for (std::size_t col = 0; col < result.rv.cols(); ++col) {
        require(std::abs(result.rv(row, col) - result.rv(col, row)) < 1e-12, "RV is not symmetric");
      }
    }
    const phylter2::Matrix wr = phylter2::dist2wr(result);
    require(wr.rows() == 4 && wr.cols() == 3, "wrong WR dimensions");
    for (const double value : wr.data()) require(std::isfinite(value) && value >= 0.0, "invalid WR value");

    const phylter2::Matrix expected_compromise = distances(
      {0, 2.332579395441830, 4.330468343019650, 5.332579395441830,
       2.332579395441830, 0, 3.330468343019650, 4.002111052422180,
       4.330468343019650, 3.330468343019650, 0, 2,
       5.332579395441830, 4.002111052422180, 2, 0});
    require(phylter2::max_abs_difference(result.compromise, expected_compromise) < 1e-11,
            "R/C++ compromise mismatch");

    phylter2::Matrix coordinate_gram(4, 4);
    for (std::size_t row = 0; row < 4; ++row) {
      for (std::size_t col = 0; col < 4; ++col) {
        for (std::size_t axis = 0; axis < 2; ++axis) {
          coordinate_gram(row, col) += result.coordinates(row, axis) * result.coordinates(col, axis);
        }
      }
    }

    const phylter2::NamedDistanceMatrix tree_distances = phylter2::patristic_distances(
      phylter2::parse_newick("((A:1,B:2):3,C:4,D:5);"));
    require(tree_distances.taxa == std::vector<std::string>({"A", "B", "C", "D"}),
            "Newick labels are not preserved");
    require_near(tree_distances.values(0, 1), 3.0, 1e-12, "wrong Newick A-B distance");
    require_near(tree_distances.values(0, 2), 8.0, 1e-12, "wrong Newick A-C distance");
    require_near(tree_distances.values(2, 3), 9.0, 1e-12, "wrong Newick C-D distance");
    const phylter2::NamedDistanceMatrix quoted_distances = phylter2::patristic_distances(
      phylter2::parse_newick("('taxon A':1,[comment]B:2,C:3);"));
    require(quoted_distances.taxa.front() == "taxon A", "quoted Newick label is not preserved");

    const phylter2::PreparationResult prepared = phylter2::prepare_matrices(
      {gene("g1", {"A", "B", "C"}, {0, 2, 4, 2, 0, 3, 4, 3, 0}),
       gene("g2", {"A", "C", "D"}, {0, 5, 8, 5, 0, 6, 8, 6, 0}),
       gene("g3", {"B", "C", "D"}, {0, 4, 7, 4, 0, 3, 7, 3, 0})},
      {.normalization = phylter2::Normalization::none});
    require(prepared.taxa == std::vector<std::string>({"A", "B", "C", "D"}),
            "common taxon order is not deterministic");
    require(prepared.matrices.size() == 3, "missing taxa changed gene count");
    // B-D occurs only in g3 and must be used to fill g1 and g2.
    require_near(prepared.matrices[0].distances.values(1, 3), 7.0, 1e-12,
                 "missing pair was not imputed from observed genes");
    // A-D occurs only in g2 and must be used to fill g1 and g3.
    require_near(prepared.matrices[2].distances.values(0, 3), 8.0, 1e-12,
                 "missing pair imputation has wrong taxon alignment");
    const phylter2::Matrix expected_coordinate_gram = distances(
      {1.632342611930640, 0.225117879925977, -0.659349470192803, -1.198111021663810,
       0.225117879925977, 1.074842295608650, -0.648581860849075, -0.651378314685555,
       -0.659349470192803, -0.648581860849075, 0.564255890011440, 0.743675441030439,
       -1.198111021663810, -0.651378314685555, 0.743675441030439, 1.105813895318930});
    require(phylter2::max_abs_difference(coordinate_gram, expected_coordinate_gram) < 1e-10,
            "R/C++ coordinate geometry mismatch");

    const std::vector<double> expected_wr_values{
      0.142223361388058, 0.112593527881982, 0.217464141735242,
      0.104800002755837, 0.115506252045624, 0.219901013994752,
      0.0837136965445153, 0.247541659876534, 0.161169074053253,
      0.0734552335816184, 0.240556088709229, 0.217019352155249};
    // R printed WR column-major; expected_wr_values above are rearranged by rows.
    for (std::size_t row = 0; row < 4; ++row) {
      for (std::size_t col = 0; col < 3; ++col) {
        require_near(wr(row, col), expected_wr_values[row * 3 + col], 1e-10,
                     "R/C++ WR mismatch");
      }
    }
  } catch (const std::exception& error) {
    std::cerr << "FAILED: " << error.what() << '\n';
    return EXIT_FAILURE;
  }
  std::cout << "PASS C++ DISTATIS core invariants\n";
}
